###
# get all products
GET http://localhost:8080/api/v1/products
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxMjM0NSIsImlhdCI6MTc2ODExNDUxNywiZXhwIjoxNzczMjk4NTE3fQ._4joRftjw_3FWgTYZTuOseOhZZfo4xkPmnJCw9uwYgDDOlVYNhq_jATujIkSEroA

###
# pagination test page 3 size 5
GET http://localhost:8080/api/v1/products?page=3&size=5
Accept: application/json

###
# get products by search
GET http://localhost:8080/api/v1/products?q=Adjustable
Accept: application/json

###
# get products by category
GET http://localhost:8080/api/v1/products?categoryId=18
Accept: application/json

###
# get products by search and category
GET http://localhost:8080/api/v1/products?q=port&categoryId=1
Accept: application/json

###
# pagination test page 0
GET http://localhost:8080/api/v1/products?page=0
Accept: application/json

###
# register new user
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json
Accept: application/json

{
    "phoneNumber": "4321",
    "name": "New User 3",
    "password": "pwd"
}

###
# login user
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json
Accept: application/json

{
    "phoneNumber": "4321",
    "password": "pwd"
}

###
#get all users
GET http://localhost:8080/api/v1/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI0MzIxIiwiaWF0IjoxNzY5MzQzNDA0LCJleHAiOjE3NzQ1Mjc0MDR9.cmJH8l2DjYkaqspgo9FNlO2E6O6gamlDX8tZOAEjb84lXtLwaGMh26G80zAxCwJN

###
# Sort products by price dess/asc
GET http://localhost:8080/api/v1/products?sort=price_desc
Accept: application/json
###

# add chart
POST http://localhost:8080/api/v1/carts
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI0MzIxIiwiaWF0IjoxNzY5MzQzNDA0LCJleHAiOjE3NzQ1Mjc0MDR9.cmJH8l2DjYkaqspgo9FNlO2E6O6gamlDX8tZOAEjb84lXtLwaGMh26G80zAxCwJN

{
  "productId": 47,
  "quantity": 5
}

###


# get charts
GET http://localhost:8080/api/v1/carts
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI0MzIxIiwiaWF0IjoxNzY5MzQzNDA0LCJleHAiOjE3NzQ1Mjc0MDR9.cmJH8l2DjYkaqspgo9FNlO2E6O6gamlDX8tZOAEjb84lXtLwaGMh26G80zAxCwJN

###

# Delete chart
DELETE http://localhost:8080/api/v1/carts
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI0MzIxIiwiaWF0IjoxNzY5MzQzNDA0LCJleHAiOjE3NzQ1Mjc0MDR9.cmJH8l2DjYkaqspgo9FNlO2E6O6gamlDX8tZOAEjb84lXtLwaGMh26G80zAxCwJN

{
  "productId": 199,
  "quantity": 1
}

###
